server:
  port: 3339


spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  # 日期返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    database: 5
#    host: 127.0.0.1
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        min-idle: 0
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#    connect-timeout: 30000ms

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/ftm-system?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
#    username: root
#    password: tyb

#mybatis-plus:
#  type-aliases-package: top.anets.module.**.entity
#  # xxxMapper.xml 路径
#  mapper-locations: classpath*:top/anets/module/**/mapper/**/*.xml

file:
  ROOT_PATH: ${user.home}/.files


secure:
  ignore:
    urls: #配置白名单路径
    - "/user/login"
    - "/qc/rectify/info"
    - "/file/getFile"
    - "/swagger-ui/"
    - "/swagger-ui/**"
    - "/webjars/**"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/v3/api-docs"
    - "/*.html"
    - "/**/*.html"
    - "/**/*.css"
    - "/**/*.js"
    - "/actuator/**"
    - "/error"
# 集成微服务的时候需要关掉安全拦截
  enable: true
  # 默认的权限验证
  authority: false
